import math
import numpy as np
import matplotlib.pyplot as plt
import weatherAPI
import realEstateAPI

apiKey = '70f56f1c5ef54c92b6e143052240303'

def calc_power(windSpeed, bladeLength):
    airDensity = 1.225 
    sweptArea = math.pi * bladeLength ** 2
    power = 0.5 * airDensity * sweptArea * (windSpeed ** 3) * 0.42
    return power

def unit_change(windSpeedKMH):
    return windSpeedKMH * (1000 / 3600)

def calc_efficiency(power, sweptArea, windSpeed):
    if windSpeed == 0:
        return 0
    efficiency = (power / (0.5 * 1.225 * sweptArea * windSpeed ** 3)) * 100
    return efficiency

def calc_energy_prodcution(power, time):
    energy = power * time
    return energy

def main():
    bladeLength = float(input("Enter blade length (meters): "))
    county = input("What county: ")
    windSpeedKMH = weatherAPI.get_wind_data(apiKey, county)[0]
    windDirection = weatherAPI.get_wind_data(apiKey, county)[1]
    time = float(input("Enter time (hours): "))
    windSpeed = unit_change(windSpeedKMH)
    sweptArea = math.pi * bladeLength ** 2

    power = calc_power(windSpeed, bladeLength)
    print("Power generated by the turbine:", power, "watts")

    efficiency = calc_efficiency(power, sweptArea, windSpeed)
    print("Efficiency of the turbine:", efficiency, "%")

    energy = calc_energy_prodcution(power, time)
    print("Energy produced by the turbine in", time, "hours:", energy, "watt hours")

if __name__ == "__main__":
    main()
